name: test - Simple CI

on:
  push:
    paths:
      - 'Application-Code/backend/**'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Optional image tag to push (defaults to commit sha)'
        required: false
        default: ''

jobs:
  docker:
    name: Build, scan and push image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}



